### PR TITLE
fix: add check on the pipeline callback `err` parameter

### LINKED ISSUE #14: Pipeline callback calls fastify.log.error even though `err` is undefined
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Plugin version

2.0.1

### Node.js version

18.19.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

Today I was experimenting with using this module, and I noticed that when this plugin is enabled, on the fastify output log, every request has an additional logged line with `"level": "50"` (an error log), with an empty message.

Example output
```
...
{"level":30,"time":1705854780559,"pid":218554,"hostname":"pop-os","reqId":"req-1","req":{"method":"GET","url":"/","hostname":"localhost:3000","remoteAddress":"::ffff:127.0.0.1","remotePort":39902},"msg":"incoming request"}
{"level":50,"time":1705854780586,"pid":218554,"hostname":"pop-os"}
{"level":30,"time":1705854780593,"pid":218554,"hostname":"pop-os","reqId":"req-1","res":{"statusCode":304},"responseTime":33.166690999642015,"msg":"request completed"}
...
```

While tracking down where it originated from, I found out that this log was added every time a stream was fully done.

I looked through the source code of the plugin, and noticed that multiple times, the `pipeline` function is used. For example in the following lines: https://github.com/fastify/fastify-throttle/blob/f3c385791486be581f5577e96113e66c2f8bb4e5/index.js#L44-L48

According to the [documentation](https://nodejs.org/api/stream.html#streampipelinesource-transforms-destination-callback) a check on the value of the `err` variable needs to be performed to asses if the pipeline terminated with an error or it was successful.

Throughout the [index.js](https://github.com/fastify/fastify-throttle/blob/master/index.js) i noticed that the check is missing in all of the pipelines. That appears to be the cause for the empty error log I noticed. In the current scenario, the value of `err` for correctly terminated pipelines is `undefined`, thus the log is without any message.

Adding the check on the err solves the issue

### Steps to Reproduce

Here is the link to a repository which reproduces the issue: https://github.com/matteosacchetto/fastify-throttle-additional-error-log

### Expected Behavior

The additional error log should not appear when the pipeline terminates correctly

### PR DESCRIPTION
**Pull request by matteosacchetto**
This PR adds the check on the `err` parameter of the pipeline callback to verify whether an error was raised or the pipeline finished successfully.

Closes #14 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

File: test/utils/error-stream.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ class ErrorStream extends Readable {
   }
 
   _read () {
-    throw new Error(this.#message)
+    this.emit('error', new Error(this.#message))
```
Comment (mcollina) [inline test/utils/error-stream.js:23]:
```suggestion
    this.destroy(new Error(this.#message))
```

File: index.js [hunk 2]
```diff
@@ -37,28 +37,29 @@ async function addRouteThrottleHook (fastify, routeOptions, throttleOptions) {
 
 function throttleOnSendHandler (fastify, throttleOpts) {
   const bytesPerSecond = throttleOpts.bytesPerSecond
+  const pipelineErrorCallback = err => { if (err) fastify.log.error(err) }
```
Comment (Uzlopak) [inline index.js:40]: I would prefer to call it pipelineCallback, because it is not only called in the error case. 
Also you can simplify the function to this:

```suggestion
  const pipelineCallback = err => err && fastify.log.error(err)
```

Other than that LGTM

Comment (matteosacchetto) [reply index.js]: Ok, I applied the suggested changes

**Review by Uzlopak — APPROVED** [review]
LGTM
